package fr.umlv.ir.dingo.tools;

import fr.umlv.ir.dingo.tools.GrammarEvaluator;
import fr.umlv.ir.dingo.tree.ArgsList;
import fr.umlv.ir.dingo.tree.BooleanExpr;
import fr.umlv.ir.dingo.tree.BooleanValue;
import fr.umlv.ir.dingo.tree.Expr;
import fr.umlv.ir.dingo.tree.ExprDefinition;
import fr.umlv.ir.dingo.tree.FunctionCall;
import fr.umlv.ir.dingo.tree.Identifier;
import fr.umlv.ir.dingo.tree.Init;
import fr.umlv.ir.dingo.tree.Instruction;
import fr.umlv.ir.dingo.tree.Instructions;
import fr.umlv.ir.dingo.tree.NumericExpr;
import fr.umlv.ir.dingo.tree.NumericValue;
import fr.umlv.ir.dingo.tree.Param;
import fr.umlv.ir.dingo.tree.ParamsList;
import fr.umlv.ir.dingo.tree.StringExpr;

public interface GrammarEvaluator {
  public void dingo_start(Identifier identifier, Instructions instructions);
  public Instructions empty_instructions_def();
  public Instructions full_instructions_def(Instructions instructions, Instruction instruction);
  public Instruction instruction_expr_def(ExprDefinition expr_def);
  public void full_var_keyword();
  public void empty_var_keyword();
  public ExprDefinition empty_type_expr_def(Identifier identifier);
  public ExprDefinition full_type_expr_def(String type, Identifier identifier);
  public ExprDefinition init_def(Init init);
  public Init full_type_init_identifier_def(String type, Identifier identifier, Expr expr);
  public Init empty_type_init_identifier_def(Identifier identifier, Expr expr);
  public Instruction function_definition(String type, Identifier identifier, ParamsList params_list, Instructions instructions);
  public StringExpr string_value_def(String stringValue);
  public NumericExpr number_value_def(NumericValue numberValue);
  public Instruction if_def(BooleanExpr booleanExpr, Instructions instructions);
  public void empty_else_bloc();
  public void full_else_bloc(Instructions instructions);
  public BooleanExpr and_def(BooleanExpr booleanExpr, BooleanExpr booleanExpr2);
  public BooleanExpr or_def(BooleanExpr booleanExpr, BooleanExpr booleanExpr2);
  public BooleanExpr equals_def(Expr expr, Expr expr2);
  public BooleanExpr not_equals_def(Expr expr, Expr expr2);
  public BooleanExpr not_def(BooleanExpr booleanExpr);
  public BooleanExpr sup_def(Expr expr, Expr expr2);
  public BooleanExpr inf_def(Expr expr, Expr expr2);
  public BooleanExpr inf_equals_def(Expr expr, Expr expr2);
  public BooleanExpr sup_equals_def(Expr expr, Expr expr2);
  public BooleanExpr booleanValue_def(BooleanValue booleanValue);
  public Instruction for_def(Init init, BooleanExpr booleanExpr, Init init2, Instructions instructions);
  public Instruction foreach_def(Identifier identifier, Identifier identifier2, Instructions instructions);
  public Instruction forever_def(Instructions instructions);
  public Instruction print_def(Expr expr);
  public Instruction println_def(Expr expr);
  public Instruction return_def(Expr expr);
  public Instruction break_def();
  public Instruction continue_def();
  public ParamsList one_param_list_def(Param param);
  public ParamsList params_list_def(Param param, ParamsList params_list);
  public ParamsList empty_params_list_def();
  public Param param_def(String type, Identifier identifier);
  public String object_type_def();
  public String numeric_type_def();
  public String string_type_def();
  public String void_type_def();
  public String array_type_def(String type);
  public String function_type_def();
  public FunctionCall function_call_def(Identifier identifier, ArgsList args_list);
  public ArgsList one_arg_list_def(Expr arg);
  public ArgsList args_list_def(Expr arg, ArgsList args_list);
  public ArgsList empty_args_list_def();
  public Expr arg_def(Expr expr);
  public Expr plus_def(Expr expr, Expr expr2);
  public Expr minus_def(Expr expr, Expr expr2);
  public Expr star_def(Expr expr, Expr expr2);
  public Expr divide_def(Expr expr, Expr expr2);
  public Expr modulo_def(Expr expr, Expr expr2);
  public Expr identifier_expr_def(Identifier identifier);
  public Expr numeric_expr_def(NumericExpr numeric_expr);
  public Expr string_expr_def(StringExpr string_expr);
  public Expr function_call_expr_def(FunctionCall function_call);
}
